//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.08 at 12:22:06 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://spring.io/ex4/webservice", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package io.spring.ex4.webservice;
