//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.08 at 12:22:06 AM CET 
//


package com.karim.Restfull.model;

import lombok.Data;

@Data
public class Offre {

    protected String id;
    protected String nomHotel;
    protected String typeChambre;
    protected String dateDisponibilite;
    protected double prix;

}
